//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistRebanho.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CADASTRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CADASTRO()
        {
            this.COBERTURA = new HashSet<COBERTURA>();
            this.MANEJO = new HashSet<MANEJO>();
            this.ORDENHA = new HashSet<ORDENHA>();
            this.PARTO = new HashSet<PARTO>();
            this.PESAGEM = new HashSet<PESAGEM>();
        }
    
        public string animal { get; set; }
        public Nullable<System.DateTime> dataNascimento { get; set; }
        public string pai { get; set; }
        public string mae { get; set; }
        public string idade { get; set; }
        public string producao { get; set; }
        public Nullable<int> crias { get; set; }
        public Nullable<System.DateTime> ultimoParto { get; set; }
        public Nullable<System.DateTime> dataDescarte { get; set; }
        public string motivoDescarte { get; set; }
        public string observaçao { get; set; }
        public Nullable<int> raca { get; set; }
    
        public virtual RACA RACA1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COBERTURA> COBERTURA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MANEJO> MANEJO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDENHA> ORDENHA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PARTO> PARTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PESAGEM> PESAGEM { get; set; }
    }
}
