//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistRebanho.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class COBERTURA
    {
        public int id { get; set; }
        public Nullable<System.DateTime> ultimoParto { get; set; }
        public Nullable<System.DateTime> cobertura { get; set; }
        public Nullable<int> del { get; set; }
        public Nullable<int> diasPosCobertura { get; set; }
        public Nullable<System.DateTime> toque { get; set; }
        public string resultadoToque { get; set; }
        public Nullable<System.DateTime> previsaoParto { get; set; }
        public Nullable<System.DateTime> secar { get; set; }
        public string animal { get; set; }
        public string observacao { get; set; }
    
        public virtual CADASTRO CADASTRO { get; set; }
    }
}
