//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistRebanho.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MANEJO
    {
        public int id { get; set; }
        public string animal { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<int> vacina { get; set; }
        public string banho { get; set; }
        public Nullable<int> diagnostico { get; set; }
        public string tratamento { get; set; }
        public string observacao { get; set; }
    
        public virtual CADASTRO CADASTRO { get; set; }
        public virtual DIAGNOSTICO DIAGNOSTICO1 { get; set; }
        public virtual VACINA VACINA1 { get; set; }
    }
}
