//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistRebanho.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RebanhoEntities : DbContext
    {
        public RebanhoEntities()
            : base("name=RebanhoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CADASTRO> CADASTRO { get; set; }
        public virtual DbSet<COBERTURA> COBERTURA { get; set; }
        public virtual DbSet<DIAGNOSTICO> DIAGNOSTICO { get; set; }
        public virtual DbSet<MANEJO> MANEJO { get; set; }
        public virtual DbSet<ORDENHA> ORDENHA { get; set; }
        public virtual DbSet<PARTO> PARTO { get; set; }
        public virtual DbSet<PESAGEM> PESAGEM { get; set; }
        public virtual DbSet<RACA> RACA { get; set; }
        public virtual DbSet<VACINA> VACINA { get; set; }
    }
}
